In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

In [3]:
import sys 
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

## Creating Arrays

In [4]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

In [6]:
arr = np.array(my_list) 

In [7]:
type(arr)

numpy.ndarray

In [8]:

    arr

array([0, 1, 2, 3, 4, 5])

In [9]:
np.arange(15) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
np.arange(3.0)  

array([0., 1., 2.])

In [11]:
np.arange(10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0, 5)

array([0, 1, 2, 3, 4])

In [13]:
np.arange(10,20) 

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
np.arange(20,10) # 1st arg < 2nd arg

array([], dtype=int32)

In [15]:
np.arange(-20,10) 

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [16]:
np.arange(-20,-10) 

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [17]:
np.arange(-16,10) 

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [18]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [19]:
np.arange()

TypeError: arange() requires stop to be specified.

In [20]:
np.arange(10,30,5)  # 10- starting from 30- end point 5 - step count

array([10, 15, 20, 25])

In [21]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [22]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [23]:
np.zeros(3) # parameter  tunning 

array([0., 0., 0.])

In [24]:
np.zeros(5, dtype=int) # hyperparameter tunning 

array([0, 0, 0, 0, 0])

In [25]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [28]:
zero = np.zeros([2,2])
zero


array([[0., 0.],
       [0., 0.]])

In [29]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [30]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [32]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [34]:
np.zeros((10,30),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [35]:
np.zeros((5,10)) # bydefaul 1arge -- will give row & 2nd arg - columns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [36]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n1)) # parameter tunning

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [37]:
n

(6, 7)

In [38]:
n1

(6, 8)

In [39]:
np.ones(3)

array([1., 1., 1.])

In [40]:
np.ones(4, dtype=int) 

array([1, 1, 1, 1])

In [41]:
np.ones(4)

array([1., 1., 1., 1.])

In [42]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [43]:


np.ones((5,4),dtype=int) # by default 5- rows & 4 - columns

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [44]:
range(5)

range(0, 5)

In [45]:
r = range(5)
r

range(0, 5)

In [46]:
for i in r:
    print(i)

0
1
2
3
4


In [47]:
list(range(5))

[0, 1, 2, 3, 4]

In [48]:
range(1,10)

range(1, 10)

In [49]:
list(range(1,10,3))

[1, 4, 7]

In [50]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [60]:
np.random.randint(2,5)

4

In [55]:
np.random.rand(5)

array([0.40401169, 0.39293164, 0.13204118, 0.16832665, 0.77040877])

In [56]:
np.random.rand(2,4)

array([[0.83726181, 0.04984936, 0.52941473, 0.99656663],
       [0.68391076, 0.51254645, 0.76094144, 0.46982965]])

In [61]:
np.random.randint(10,20,5)

array([16, 14, 16, 14, 19])

In [63]:
pb=np.random.randint(10,20,4)
pb

array([13, 14, 19, 12])

In [64]:
np.random.randint(10,40,(10,10)) #generre the element 10 -30 with 4*4 mtri

array([[12, 28, 33, 37, 15, 14, 25, 19, 39, 28],
       [17, 28, 13, 17, 37, 23, 25, 20, 10, 10],
       [32, 16, 38, 10, 15, 15, 32, 36, 29, 15],
       [15, 25, 12, 35, 31, 33, 12, 30, 30, 18],
       [39, 27, 26, 35, 38, 21, 33, 28, 22, 39],
       [20, 14, 32, 12, 29, 27, 17, 12, 39, 25],
       [23, 25, 22, 32, 38, 34, 10, 11, 35, 24],
       [10, 33, 39, 21, 22, 17, 26, 19, 10, 22],
       [13, 39, 14, 25, 29, 38, 16, 14, 25, 27],
       [19, 10, 28, 29, 15, 13, 23, 14, 38, 15]])

In [65]:
np.random.randint(1,100,(12,12)) #generre the element 10 -30 with 4*4 mtri

array([[51, 88, 48, 47, 76, 41, 14, 87, 68, 73,  5, 59],
       [ 8, 63, 55, 34, 84, 72, 51, 44,  5, 89, 37, 48],
       [22, 85, 32, 29, 28, 96, 10, 21, 45, 33,  7, 83],
       [ 2, 78, 53, 51, 21, 97, 48, 69,  1, 50, 37, 24],
       [54, 12,  7, 66, 35,  5, 28, 63, 96, 11, 92, 31],
       [85, 91, 65, 64, 76, 74, 95, 59, 87,  3, 92, 53],
       [28, 67, 96,  4, 42,  4,  1, 49, 60, 21, 97, 64],
       [32, 44, 88,  7, 25, 98, 54, 85,  4, 58, 41,  9],
       [44, 34, 71,  5, 81,  5, 43, 62, 51, 87, 56, 89],
       [60, 93, 47, 55, 60, 57,  6, 52, 57, 78,  6, 82],
       [38, 56, 16, 99, 20, 70, 31, 97,  1, 24, 52, 49],
       [72, 78, 79, 56, 31, 34,  5, 62,  3, 95, 66, 14]])

In [68]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [69]:
np.arange(1,25).reshape(6,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [75]:
b = np.random.randint(10,20,(5,4))

In [76]:
b

array([[11, 14, 12, 10],
       [10, 13, 15, 18],
       [19, 17, 11, 14],
       [13, 13, 15, 11],
       [14, 10, 12, 10]])

In [73]:
b=np.random.randint(10,20,(5,4)).reshape(4,5)

In [74]:
b

array([[12, 14, 13, 13, 15],
       [15, 13, 15, 18, 12],
       [16, 11, 18, 14, 15],
       [13, 15, 11, 16, 11]])

In [77]:
b

array([[11, 14, 12, 10],
       [10, 13, 15, 18],
       [19, 17, 11, 14],
       [13, 13, 15, 11],
       [14, 10, 12, 10]])

In [78]:
b[:] 

array([[11, 14, 12, 10],
       [10, 13, 15, 18],
       [19, 17, 11, 14],
       [13, 13, 15, 11],
       [14, 10, 12, 10]])

In [83]:
b[1:3]

array([[10, 13, 15, 18],
       [19, 17, 11, 14]])

In [80]:
b[2:3]

array([[19, 17, 11, 14]])

In [84]:
b

array([[11, 14, 12, 10],
       [10, 13, 15, 18],
       [19, 17, 11, 14],
       [13, 13, 15, 11],
       [14, 10, 12, 10]])

In [82]:
b[0:-2] 

array([[11, 14, 12, 10],
       [10, 13, 15, 18],
       [19, 17, 11, 14]])

In [86]:
b[0:2] 

array([[11, 14, 12, 10],
       [10, 13, 15, 18]])

In [90]:
b

array([[11, 14, 12, 10],
       [10, 13, 15, 18],
       [19, 17, 11, 14],
       [13, 13, 15, 11],
       [14, 10, 12, 10]])

In [95]:
b[1:3]

array([[10, 13, 15, 18],
       [19, 17, 11, 14]])

In [94]:
b[2:2]

array([], shape=(0, 4), dtype=int32)

In [99]:
b[4,3]

10

## Operations

In [101]:
a = np.random.randint(10,20,10)

In [102]:
a

array([15, 12, 18, 13, 14, 11, 19, 16, 11, 12])

In [103]:
id(a)

2254577943056

In [104]:
arr

array([0, 1, 2, 3, 4, 5])

In [105]:
arr2 = np.random.randint(0,100,(10,10))

In [106]:
arr2

array([[13, 45, 60, 40, 33, 84, 26, 85, 23,  8],
       [33, 54, 53, 28, 81, 75, 88, 94, 54, 25],
       [59, 85, 19,  8,  1, 93, 37, 49, 60,  1],
       [ 1, 35, 18, 87, 54, 36, 55,  7, 30,  2],
       [12, 49, 27, 61, 78, 45, 11, 86, 39, 10],
       [47, 13, 97, 25, 81, 97, 37,  6, 83, 85],
       [42,  3, 24, 65,  4, 10, 33, 29, 95, 54],
       [76, 73, 17, 74, 70, 49, 15, 71,  7, 31],
       [24, 75, 75, 55, 51, 12, 46, 47, 74, 67],
       [59, 73, 53, 94, 98,  2, 11, 85, 98, 81]])

In [107]:
arr2[0:5] 

array([[13, 45, 60, 40, 33, 84, 26, 85, 23,  8],
       [33, 54, 53, 28, 81, 75, 88, 94, 54, 25],
       [59, 85, 19,  8,  1, 93, 37, 49, 60,  1],
       [ 1, 35, 18, 87, 54, 36, 55,  7, 30,  2],
       [12, 49, 27, 61, 78, 45, 11, 86, 39, 10]])

In [108]:
arr2

array([[13, 45, 60, 40, 33, 84, 26, 85, 23,  8],
       [33, 54, 53, 28, 81, 75, 88, 94, 54, 25],
       [59, 85, 19,  8,  1, 93, 37, 49, 60,  1],
       [ 1, 35, 18, 87, 54, 36, 55,  7, 30,  2],
       [12, 49, 27, 61, 78, 45, 11, 86, 39, 10],
       [47, 13, 97, 25, 81, 97, 37,  6, 83, 85],
       [42,  3, 24, 65,  4, 10, 33, 29, 95, 54],
       [76, 73, 17, 74, 70, 49, 15, 71,  7, 31],
       [24, 75, 75, 55, 51, 12, 46, 47, 74, 67],
       [59, 73, 53, 94, 98,  2, 11, 85, 98, 81]])

In [109]:
arr2[1,4] 

81

In [110]:
arr2

array([[13, 45, 60, 40, 33, 84, 26, 85, 23,  8],
       [33, 54, 53, 28, 81, 75, 88, 94, 54, 25],
       [59, 85, 19,  8,  1, 93, 37, 49, 60,  1],
       [ 1, 35, 18, 87, 54, 36, 55,  7, 30,  2],
       [12, 49, 27, 61, 78, 45, 11, 86, 39, 10],
       [47, 13, 97, 25, 81, 97, 37,  6, 83, 85],
       [42,  3, 24, 65,  4, 10, 33, 29, 95, 54],
       [76, 73, 17, 74, 70, 49, 15, 71,  7, 31],
       [24, 75, 75, 55, 51, 12, 46, 47, 74, 67],
       [59, 73, 53, 94, 98,  2, 11, 85, 98, 81]])

In [111]:
arr2[-5,5] 

97

In [114]:
arr2

array([[13, 45, 60, 40, 33, 84, 26, 85, 23,  8],
       [33, 54, 53, 28, 81, 75, 88, 94, 54, 25],
       [59, 85, 19,  8,  1, 93, 37, 49, 60,  1],
       [ 1, 35, 18, 87, 54, 36, 55,  7, 30,  2],
       [12, 49, 27, 61, 78, 45, 11, 86, 39, 10],
       [47, 13, 97, 25, 81, 97, 37,  6, 83, 85],
       [42,  3, 24, 65,  4, 10, 33, 29, 95, 54],
       [76, 73, 17, 74, 70, 49, 15, 71,  7, 31],
       [24, 75, 75, 55, 51, 12, 46, 47, 74, 67],
       [59, 73, 53, 94, 98,  2, 11, 85, 98, 81]])

In [113]:
arr2[3:4]

array([[ 1, 35, 18, 87, 54, 36, 55,  7, 30,  2]])

In [115]:
arr2[2:6]

array([[59, 85, 19,  8,  1, 93, 37, 49, 60,  1],
       [ 1, 35, 18, 87, 54, 36, 55,  7, 30,  2],
       [12, 49, 27, 61, 78, 45, 11, 86, 39, 10],
       [47, 13, 97, 25, 81, 97, 37,  6, 83, 85]])

In [116]:
arr2[::-1]

array([[59, 73, 53, 94, 98,  2, 11, 85, 98, 81],
       [24, 75, 75, 55, 51, 12, 46, 47, 74, 67],
       [76, 73, 17, 74, 70, 49, 15, 71,  7, 31],
       [42,  3, 24, 65,  4, 10, 33, 29, 95, 54],
       [47, 13, 97, 25, 81, 97, 37,  6, 83, 85],
       [12, 49, 27, 61, 78, 45, 11, 86, 39, 10],
       [ 1, 35, 18, 87, 54, 36, 55,  7, 30,  2],
       [59, 85, 19,  8,  1, 93, 37, 49, 60,  1],
       [33, 54, 53, 28, 81, 75, 88, 94, 54, 25],
       [13, 45, 60, 40, 33, 84, 26, 85, 23,  8]])

In [117]:
arr2[::-1]

array([[59, 73, 53, 94, 98,  2, 11, 85, 98, 81],
       [24, 75, 75, 55, 51, 12, 46, 47, 74, 67],
       [76, 73, 17, 74, 70, 49, 15, 71,  7, 31],
       [42,  3, 24, 65,  4, 10, 33, 29, 95, 54],
       [47, 13, 97, 25, 81, 97, 37,  6, 83, 85],
       [12, 49, 27, 61, 78, 45, 11, 86, 39, 10],
       [ 1, 35, 18, 87, 54, 36, 55,  7, 30,  2],
       [59, 85, 19,  8,  1, 93, 37, 49, 60,  1],
       [33, 54, 53, 28, 81, 75, 88, 94, 54, 25],
       [13, 45, 60, 40, 33, 84, 26, 85, 23,  8]])

In [118]:
arr2[::-2]

array([[59, 73, 53, 94, 98,  2, 11, 85, 98, 81],
       [76, 73, 17, 74, 70, 49, 15, 71,  7, 31],
       [47, 13, 97, 25, 81, 97, 37,  6, 83, 85],
       [ 1, 35, 18, 87, 54, 36, 55,  7, 30,  2],
       [33, 54, 53, 28, 81, 75, 88, 94, 54, 25]])

In [119]:
arr

array([0, 1, 2, 3, 4, 5])

In [120]:
arr.max()

5

In [121]:
arr.min()

0

In [122]:
arr.mean()

2.5

In [125]:
from numpy import *
a=arr
median(a)

2.5

In [126]:
arr

array([0, 1, 2, 3, 4, 5])

In [127]:
arr

array([0, 1, 2, 3, 4, 5])

In [128]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [129]:
arr.reshape(6,1)  

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [130]:
arr.reshape(2,3,order='C') 

array([[0, 1, 2],
       [3, 4, 5]])

In [131]:
arr.reshape(2,3,order='F') # print element with fortran 

array([[0, 2, 4],
       [1, 3, 5]])

In [132]:
arr.reshape(2,3,order='A') # print element with fortran 

array([[0, 1, 2],
       [3, 4, 5]])

## Indexing

In [134]:
mat=np.arange(0,100).reshape(10,10)

In [137]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [136]:
row = 4
col = 5

In [138]:
mat[row,col] 

45

In [139]:
mat[4,5] 

45

In [140]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [141]:
mat[6] # befault it represent to rows

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [142]:
col=6

In [143]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [144]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [145]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [146]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [147]:
mat[4,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [148]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

## Masking

In [149]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [150]:
mat[mat==50]

array([50])

# 1. Array Creation Functions

In [151]:
import numpy as np

In [153]:
arr

array([0, 1, 2, 3, 4, 5])

In [154]:
# Create an array from a list
a = np.array([1, 2, 3])
print("Array a:", a)

Array a: [1 2 3]


In [155]:
# Create an array with evenly spaced values
b = np.arange(0, 10, 2)  # Values from 0 to 10 with step 2
print("Array b:", b)

Array b: [0 2 4 6 8]


In [156]:
# Create an array with linearly spaced values
c = np.linspace(0, 1, 5)  # 5 values evenly spaced between 0 and 1
print("Array c:", c)

Array c: [0.   0.25 0.5  0.75 1.  ]


In [157]:
# Create an array filled with zeros
d = np.zeros((2, 3))  # 2x3 array of zeros
print("Array d:\n", d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [158]:
# Create an array filled with ones
e = np.ones((3, 2))  # 3x2 array of ones
print("Array e:\n", e)

Array e:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [160]:
 #Create an identity matrix
f = np.eye(4,dtype=int)  # 4x4 identity matrix
print("Identity matrix f:\n", f)

Identity matrix f:
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


# 2. Array Manipulation Functions

In [161]:
# Reshape an array
a1 = np.array([1, 2, 3])
reshaped = np.reshape(a1, (1, 3))  # Reshape to 1x3
print("Reshaped array:", reshaped)

Reshaped array: [[1 2 3]]


In [162]:
# Flatten an array
f1 = np.array([[1, 2], [3, 4]])
flattened = np.ravel(f1)  # Flatten to 1D array
print("Flattened array:", flattened)

Flattened array: [1 2 3 4]


In [163]:
# Transpose an array
e1 = np.array([[1, 2], [3, 4]])
transposed = np.transpose(e1)  # Transpose the array
print("Transposed array:\n", transposed)

Transposed array:
 [[1 3]
 [2 4]]


In [164]:
# Stack arrays vertically
a2 = np.array([1, 2])
b2 = np.array([3, 4])
stacked = np.vstack([a2, b2])  # Stack a and b vertically
print("Stacked arrays:\n", stacked)

Stacked arrays:
 [[1 2]
 [3 4]]


# 3. Mathematical Functions

In [165]:
# Add two arrays
g = np.array([1, 2, 3, 4])
added = np.add(g, 2)  # Add 2 to each element
print("Added 2 to g:", added)

Added 2 to g: [3 4 5 6]


In [166]:
# Square each element
squared = np.power(g, 2)  # Square each element
print("Squared g:", squared)

Squared g: [ 1  4  9 16]


In [167]:
# Square root of each element
sqrt_val = np.sqrt(g)  # Square root of each element
print("Square root of g:", sqrt_val)

Square root of g: [1.         1.41421356 1.73205081 2.        ]


In [168]:
print(a1)
print(g)

[1 2 3]
[1 2 3 4]


In [169]:
# Dot product of two arrays
a2 = np.array([1, 2, 3])
dot_product = np.dot(a2, g)  # Dot product of a and g
print("Dot product of a and g:", dot_product)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [170]:
print(a)
print(a1)

[1 2 3]
[1 2 3]


In [171]:
a3 = np.array([1, 2, 3])
dot_product = np.dot(a1, a)  # Dot product of a and g
print("Dot product of a1 and a:", dot_product)

Dot product of a1 and a: 14


# 4. Statistical Functions

In [172]:
s = np.array([1, 2, 3, 4])
mean = np.mean(s)
print("Mean of s:", mean)

Mean of s: 2.5


In [173]:
# Standard deviation of an array
std_dev = np.std(s)
print("Standard deviation of s:", std_dev)

Standard deviation of s: 1.118033988749895


In [174]:
# Minimum element of an array
minimum = np.min(s)
print("Min of s:", minimum)

Min of s: 1


In [175]:
# Maximum element of an array
maximum = np.max(s)
print("Max of s:", maximum)

Max of s: 4


# 5. Linear Algebra Functions

In [176]:
# Create a matrix
matrix = np.array([[1, 2], [3, 4]])

In [177]:
matrix

array([[1, 2],
       [3, 4]])

In [178]:
# Determinant of a matrix
determinant = np.linalg.det(matrix)
print("Determinant of matrix:", determinant)

Determinant of matrix: -2.0000000000000004


In [179]:
# Inverse of a matrix
inverse = np.linalg.inv(matrix)
print("Inverse of matrix:\n", inverse)

Inverse of matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


# 6. Random Sampling Functions

In [180]:
# Generate random values between 0 and 1
random_vals = np.random.rand(3)  # Array of 3 random values between 0 and 1
print("Random values:", random_vals)

Random values: [0.29974491 0.10994314 0.81634218]


In [181]:
# Set seed for reproducibility
np.random.seed(0)

# Generate random values between 0 and 1
random_vals = np.random.rand(3)  # Array of 3 random values between 0 and 1
print("Random values:", random_vals)

Random values: [0.5488135  0.71518937 0.60276338]


In [182]:
# Generate random integers
rand_ints = np.random.randint(0, 10, size=5)  # Random integers between 0 and 10
print("Random integers:", rand_ints)

Random integers: [3 7 9 3 5]


In [183]:
# Set seed for reproducibility
np.random.seed(0)

# Generate random integers
rand_ints = np.random.randint(0, 10, size=5)  # Random integers between 0 and 10
print("Random integers:", rand_ints)

Random integers: [5 0 3 3 7]


# 7. Boolean & Logical Functions

In [184]:
# Check if all elements are True
# all
logical_test = np.array([True, False, True])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [185]:
# Check if all elements are True
logical_test = np.array([True, False, True])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [186]:
# Check if all elements are True
logical_test = np.array([False, False, False])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [187]:
# Check if any elements are True
# any
any_true = np.any(logical_test)  # Check if any are True
print("Any elements True:", any_true)

Any elements True: False


# 8. Set Operations

In [188]:
# Intersection of two arrays
set_a = np.array([1, 2, 3, 4])
set_b = np.array([3, 4, 5, 6])
intersection = np.intersect1d(set_a, set_b)
print("Intersection of a and b:", intersection)

Intersection of a and b: [3 4]


In [189]:
# Union of two arrays
union = np.union1d(set_a, set_b)
print("Union of a and b:", union)

Union of a and b: [1 2 3 4 5 6]


# 9. Array Attribute Functions

In [190]:
# Array attributes
a = np.array([1, 2, 3])
shape = a.shape  # Shape of the array
size = a.size    # Number of elements
dimensions = a.ndim  # Number of dimensions
dtype = a.dtype   # Data type of the array

print("Shape of a:", shape)
print("Size of a:", size)
print("Number of dimensions of a:", dimensions)
print("Data type of a:", dtype)

Shape of a: (3,)
Size of a: 3
Number of dimensions of a: 1
Data type of a: int32


# 10. Other Functions

In [191]:
# Create a copy of an array
a = np.array([1, 2, 3])
copied_array = np.copy(a)  # Create a copy of array a
print("Copied array:", copied_array)

Copied array: [1 2 3]


In [192]:
# Size in bytes of an array
array_size_in_bytes = a.nbytes  # Size in bytes
print("Size of a in bytes:", array_size_in_bytes)

Size of a in bytes: 12


In [193]:
# Check if two arrays share memory
shared = np.shares_memory(a, copied_array)  # Check if arrays share memory
print("Do a and copied_array share memory?", shared)

Do a and copied_array share memory? False
