In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

In [3]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [4]:
type(my_list)

list

In [5]:
arr = np.array(my_list) 

In [6]:
arr

array([0, 1, 2, 3, 4, 5])

In [7]:
type(arr)

numpy.ndarray

In [8]:
np.arange(15) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
np.arange(3.0)  

array([0., 1., 2.])

In [10]:
np.arange(10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(10,dtype=int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(-20,10) 

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [13]:
np.arange(30,20)  # 1st arg always be < then 2nd arg

array([], dtype=int32)

In [14]:
np.arange(10,30,5)  # 10- starting from 30- end point 5 - step count

array([10, 15, 20, 25])

In [15]:
np.zeros(3) # parameter  tunning 

array([0., 0., 0.])

In [16]:
np.zeros(5, dtype=int) # hyperparameter tunning 

array([0, 0, 0, 0, 0])

In [17]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [18]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [19]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
np.zeros((2,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [21]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [23]:
np.zeros((5,20),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [24]:
np.zeros((10,30),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [25]:
np.ones(3)

array([1., 1., 1.])

In [26]:
np.ones((3),dtype=int)

array([1, 1, 1])

In [27]:
np.twos(3)# Only Zero and 1 can be printed

AttributeError: module 'numpy' has no attribute 'twos'

In [28]:
rand(3,2)# only Function

NameError: name 'rand' is not defined

In [29]:
np.rand(3,2)# module.function

AttributeError: module 'numpy' has no attribute 'rand'

In [34]:
np.random.rand(3,2)# Correct way to print random number(#package.module.function)

array([[0.19585056, 0.5969282 ],
       [0.95405773, 0.59041777],
       [0.93953195, 0.74372111]])

In [38]:
np.random.rand(3,3)

array([[0.51767205, 0.99000938, 0.66725522],
       [0.42972241, 0.38825504, 0.45736088],
       [0.1179779 , 0.34226703, 0.8546449 ]])

In [42]:
np.random.randint(2,5)

2

In [47]:
np.random.randint(2,20)#Random output in a rannge

11

In [53]:
np.random.randint(0,1)

0

In [60]:
np.random.randint(0,20,3)

array([12, 19, 18])

In [70]:
np.random.randint(1,6,(4,4))

array([[4, 5, 5, 2],
       [2, 2, 1, 1],
       [3, 4, 2, 2],
       [1, 4, 5, 2]])

In [63]:
np.random.randint(10,40,(10,10))

array([[27, 14, 36, 25, 23, 17, 20, 28, 21, 37],
       [39, 32, 26, 18, 33, 16, 12, 31, 22, 39],
       [19, 35, 20, 12, 11, 16, 18, 25, 13, 36],
       [24, 29, 27, 27, 18, 23, 20, 38, 23, 26],
       [22, 33, 34, 29, 20, 17, 11, 17, 22, 16],
       [35, 29, 10, 12, 21, 35, 18, 25, 35, 17],
       [18, 39, 22, 33, 11, 35, 30, 28, 19, 32],
       [33, 32, 16, 19, 24, 38, 24, 32, 31, 28],
       [27, 16, 38, 28, 36, 35, 25, 23, 39, 12],
       [11, 33, 17, 35, 24, 39, 10, 32, 21, 11]])

In [69]:
np.random.randint(5,9) 

8

In [66]:
np.random.randint(20,30,10)

array([22, 24, 20, 29, 25, 28, 27, 21, 26, 27])

In [72]:
np.random.randint(1,100,(12,12))

array([[25, 77, 33,  2, 72, 18, 26, 89, 11, 32, 55, 58],
       [25,  2,  4, 89, 16, 10, 23, 54, 92, 58, 11, 25],
       [35, 72, 72, 19, 24, 18, 19, 42, 41,  7, 66, 11],
       [90, 51, 88, 43, 22, 57, 75, 56, 97, 41, 39, 35],
       [25, 55, 84, 59,  4, 51, 93, 82, 70, 62, 11,  1],
       [70, 42, 30, 67, 24, 67, 82, 26,  1, 47, 45, 70],
       [84,  6, 75, 14, 83, 81, 51, 57, 32, 61, 31,  8],
       [ 2, 28, 95,  7,  6, 79, 13, 56, 87, 60,  6, 15],
       [96, 46, 25,  2, 10, 62, 70,  7, 86, 28, 59, 93],
       [72, 34, 50, 33, 14,  8,  7, 49, 62, 18, 70,  3],
       [98, 51, 84, 41, 75,  9, 27, 28, 43, 22, 16, 30],
       [97, 42, 35, 23, 55, 80, 92, 60, 26, 60,  1, 92]])

In [74]:
np.arange(1,13).reshape(3,4)# Reshape

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [75]:
np.arange(1,13).reshape(5,4)#5*4 is 20 but we have only 12 element

ValueError: cannot reshape array of size 12 into shape (5,4)

In [76]:
np.arange(1,13).reshape(6,2)# Reshape

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [119]:
np.arange(1,13).reshape(12,1)# Reshape

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [78]:
np.arange(1,13).reshape(1,12)# Reshape

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [79]:
b=np.random.randint(10,20,(5,4))

In [80]:
b

array([[15, 15, 13, 15],
       [15, 12, 16, 11],
       [19, 11, 11, 17],
       [11, 10, 10, 18],
       [11, 11, 14, 17]])

In [81]:
type(b)

numpy.ndarray

In [82]:
b[:]#slicing

array([[15, 15, 13, 15],
       [15, 12, 16, 11],
       [19, 11, 11, 17],
       [11, 10, 10, 18],
       [11, 11, 14, 17]])

In [84]:
b[1:3]# as it's slicing it will print 1 row 2 column

array([[15, 12, 16, 11],
       [19, 11, 11, 17]])

In [86]:
b[1,2]#indexing

16

In [87]:
b[1,3]

11

In [88]:
b[1,-1]

11

In [89]:
b[2:3]

array([[19, 11, 11, 17]])

In [90]:
b[0:-2]

array([[15, 15, 13, 15],
       [15, 12, 16, 11],
       [19, 11, 11, 17]])

In [91]:
b[-4,2]

16

In [ ]:
#Operations

In [94]:
 a=np.random.randint(10,20,10)

In [95]:
id(a)

1183463097424

In [96]:
arr2 = np.random.randint(0,100,(10,10))

In [97]:
arr2

array([[29, 92, 26, 71, 64, 77, 97, 67, 53, 15],
       [15, 48, 30,  9, 85, 67, 81, 41, 51, 75],
       [50, 68, 16, 29, 12,  7, 93, 69, 90,  3],
       [49, 57, 55, 85, 24, 18, 92, 49, 44, 56],
       [12, 18,  6, 49, 95, 46, 41, 83, 43,  5],
       [62, 95, 19, 78, 77, 54, 92, 38, 40,  9],
       [58, 86, 67, 87,  9,  7, 85, 24, 57, 52],
       [75, 19, 58,  4, 23, 94, 61, 35, 88, 51],
       [68, 88, 27,  5, 94, 90, 17, 56, 67, 64],
       [14, 18, 35, 73, 48, 38, 34, 97, 48, 16]])

In [99]:
arr2[::-1]# Reverse indexing can be done

array([[14, 18, 35, 73, 48, 38, 34, 97, 48, 16],
       [68, 88, 27,  5, 94, 90, 17, 56, 67, 64],
       [75, 19, 58,  4, 23, 94, 61, 35, 88, 51],
       [58, 86, 67, 87,  9,  7, 85, 24, 57, 52],
       [62, 95, 19, 78, 77, 54, 92, 38, 40,  9],
       [12, 18,  6, 49, 95, 46, 41, 83, 43,  5],
       [49, 57, 55, 85, 24, 18, 92, 49, 44, 56],
       [50, 68, 16, 29, 12,  7, 93, 69, 90,  3],
       [15, 48, 30,  9, 85, 67, 81, 41, 51, 75],
       [29, 92, 26, 71, 64, 77, 97, 67, 53, 15]])

In [100]:
arr2[::-2]

array([[14, 18, 35, 73, 48, 38, 34, 97, 48, 16],
       [75, 19, 58,  4, 23, 94, 61, 35, 88, 51],
       [62, 95, 19, 78, 77, 54, 92, 38, 40,  9],
       [49, 57, 55, 85, 24, 18, 92, 49, 44, 56],
       [15, 48, 30,  9, 85, 67, 81, 41, 51, 75]])

In [102]:
arr2[::-3]

array([[14, 18, 35, 73, 48, 38, 34, 97, 48, 16],
       [58, 86, 67, 87,  9,  7, 85, 24, 57, 52],
       [49, 57, 55, 85, 24, 18, 92, 49, 44, 56],
       [29, 92, 26, 71, 64, 77, 97, 67, 53, 15]])

In [103]:
arr2[:-3]

array([[29, 92, 26, 71, 64, 77, 97, 67, 53, 15],
       [15, 48, 30,  9, 85, 67, 81, 41, 51, 75],
       [50, 68, 16, 29, 12,  7, 93, 69, 90,  3],
       [49, 57, 55, 85, 24, 18, 92, 49, 44, 56],
       [12, 18,  6, 49, 95, 46, 41, 83, 43,  5],
       [62, 95, 19, 78, 77, 54, 92, 38, 40,  9],
       [58, 86, 67, 87,  9,  7, 85, 24, 57, 52]])

In [104]:
arr2.max()

97

In [105]:
arr2.min()

3

In [107]:
arr2.mean()

50.58

In [110]:
arr2.mean()

50.58

In [113]:
arr2.median()# it's not in function

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [114]:
# Modules are two type
#1.Inbuild and 2.user defined

In [115]:
from numpy import *
a=array([1,2,3,4,9])
median(a)

3.0

In [117]:
 #Reshaping 3 format
#1.Order-C
#2.Order-a
#3.Order-f

In [120]:
arr

array([0, 1, 2, 3, 4, 5])

In [128]:
arr.reshape(2,3,order='c')# system consider it as C type

array([[0, 1, 2],
       [3, 4, 5]])

In [129]:
arr.reshape(2,3,order='f')# F type indexing

array([[0, 2, 4],
       [1, 3, 5]])

In [125]:
arr.reshape(2,3,order='a')# A type indexing

array([[0, 1, 2],
       [3, 4, 5]])

In [130]:
mat = np.arange(0,100).reshape(10,10) 

In [131]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [132]:
row=4
col=5

In [133]:
col

5

In [134]:
row

4

In [135]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [136]:
mat[4,5]#(row,column)

45

In [137]:
mat[6]# To print Row

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [138]:
mat[:,col]# To print column

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [139]:
mat[:,5]

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [143]:
mat[row,:]# row printinhg

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [142]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [144]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [145]:
mat[1:2,2:4]

array([[12, 13]])

In [146]:
mat[2:3,2:3]

array([[22]])

In [147]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

In [149]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

In [150]:
# Masking

In [151]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [152]:
id(mat)

1183479115920

In [153]:
mat[mat<(50)]# Prining of number <50

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [159]:
mat[mat<=(50)]# less than equal to 50

SyntaxError: incomplete input (1600717723.py, line 1)

In [158]:
mat[mat>50]# prining greater than 50

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [156]:
mat[mat!=50]# Not euqal to 50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])